# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    platform.entity.user.class: AppBundle\Entity\Estabelecimento
    platform.user.provider.class: AppBundle\Provider\EstabelecimentoProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    session.handler.pdo:
            class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
            public:    false
            arguments:
                # read from parameters.yml
                - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
                - { db_username: %database_user%, db_password: %database_password% }


    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: ["%platform.entity.user.class%"]

    platform.user.repository:
        class: AppBundle\Entity\EstabelecimentoRepository
        factory_service: platform.user.manager
        factory_method: getRepository
        arguments: ["%platform.entity.user.class%"]

    platform.user.provider:
        class: %platform.user.provider.class%
        arguments:
            - "@platform.user.repository"
