# http://symfony.com/doc/current/book/doctrine.html#book-doctrine-field-types
# http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html
AppBundle\Entity\AccessToken:
    type: entity
    table: access_token
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                nullable: false
                name: client_id
                referencedColumnName: id
                onDelete: CASCADE

        estabelecimento_id:
            targetEntity: Estabelecimento
            joinColumn:
                # true to debug only
                nullable: true
                name: estabelecimento_id
                referencedColumnName: id
                onDelete: CASCADE